### ISSUE TITLE
Error : spécification de version incorrecte ‘0,7’

### ISSUE THREAD

**Issue by lost-geographer** [juba/explor#10]
Hi,

I just ran explor with this command `explor(acm_résutats)` and I get an error as shown below : 
```
Listening on http://127.0.0.1:7428
Warning: Error in : spécification de version incorrecte ‘0,7’
Stack trace (innermost first):
    4: <Anonymous>
    3: do.call
    2: print.shiny.appobj
    1: <Promise>
Error : spécification de version incorrecte ‘0,7’
```
I cannot understand which program version it is talking about. I used explor (0.3.1) on R (3.3.2) trough RStudio (1.0.44). All loaded packages are up-to-date and above 0.7.

**Comment by lost-geographer** [comment]
The error comes from the fact that I use commas as decimal separator with this option : `options(OutDec= ",")`. Replacing the comma with a point solves the issue.

**Comment by juba** [comment]
Glad you fixed the issue, I took a quick look at it but didn't really see where it could come from.

Thanks for letting me now.

**Comment by lost-geographer** [comment]
You are welcome. You can reproduce the bug with this code :
```
library(FactoMineR)
library(explor)

options(OutDec= ",")

data(tea)
mca_results = MCA(tea, quanti.sup=19, quali.sup=c(20:36))

explor(mca_results)
```
Actually, most of the people would have used `write.csv2()` in order to get comma separated decimals outputs, without changing global options.
