### ISSUE TITLE
Variables qualitatives

### ISSUE THREAD

**Issue by CroixJeremy2** [juba/explor#15]
Bonjour juba (^.^)/ Je laisse le message en français car je ne suis pas un expert en langage R, et je pense que mon problème ne viens pas de ton package, mais d'une erreur de manipulation venant de ma part. J'ai effectué une ACP va la fonction PCA du package FactoMineR
data("M")
acp1=PCA(M, quali.sup=9, scale.unit=T, ncp=3 ,graph=F)
explor(acp1)
La variable qualitative étant dans ma 9ème colonne de mon tableau M
Le problème est que je n'arrive pas à afficher les couleurs relatives aux variables qualitatives pour chaque individu sur le graphique des individu d'explor, je ne trouve pas non plus comment créer les ellipses de confiances sur explor... Je dois probablement faire une erreur de manipulation à un endroit puisque sur le .GIF de présentation, on peut apparemment avoir des couleurs, mais je ne trouve pas :( 

Si tu prends le temps de répondre, merci d'avance ! (^.^)

PS: je traduirai bien sur le message quand j'aurais un peu plus de temps (pardonne moi pour le moment :) )

**Comment by juba** [comment]
Bonjour,

Pas de souci pour le message en français, et pas la peine de le traduire plus tard :)

Alors, quelques questions :

- Est-ce que tu utilises bien la dernière version d'explor ? 
- Tu n'as pas d'erreur quand tu fais ton ACP ? 
- Et qu'est-ce que donne `acp1$quali.sup` ?

**Comment by CroixJeremy2** [comment]
Je tiens tout d'abord à te remercier pour la rapidité de la réponse ;) (j'avoue, je ne m'y attendais pas trop, et pensais envoyer ce message comme une bouteille à la mer :D )
Ensuite, j'avais oublié de préciser quelque chose d'important: je travaille avec R Studio.
Et une autre chose importante, je débute sous R, j’espère donc que je serais le plus précis possible :)

- J'ai téléchargé pour la première fois explor hier, donc je ne pense pas que le problème vienne de là. J'ai tout de même vérifié dans R studio qui m'a dit que oui c'est la dernière version. Et dans un doute extrême, j'ai réinstallé explor ce soir pour être sûr à 100% (^.^). Par contre, cela me viens à l'esprit, mais il y aurait-il d'autres packages à installer afin de faire fonctionner correctement explor ? (le problème pourrait venir de là)

- Avant de "tomber" (un peu au hasard je l'avoue) sur explor et sur FactorMineR, j'utilisais les packages fournis par ma prof, c'est à dire ade4. Ainsi, sous R Studio, j'ai vu via les graphiques "classiques" de R Studio à quoi devaient ressembler les résultats de mon ACP (sans variables qualitatives donc). Et quand j'ai découvert FactoMineR et ensuite explor, je retombais sur les mêmes résultats: à savoir, même graphique des individus, même % d'inertie, et même cercles des corrélations selon les axes retenus. J'étais tout content de voir que j'étais tombé sur le Saint Graal de l'ACP en voyant le .GIF, et je me suis demandé: "mais, tiens ! Je pourrais regrouper mes individus avec explor par couleur en créant une variable qualitative, et voir même via des ellipses comme sur le .GIF ! Bon, là ça ne marche pas pour le moment, mais peut être bientôt ^.^

- Avant tout, pour rester le moins flou possible, mon tableau de données (un data.frame) est assez basique: 14 individus en lignes (des noms d'espèces de mammifères) pour 9 variables en colonnes (T°corporelle moyenne, %graisse, etc...) donc 1 variable qualitative supplémentaire (la 9ème) que j'ai rajouté (genre de chaque individu, exemple: plusieurs espèces d'otaries sont regroupés dans cette variables en "otarie"). Et l'ACP m'indique qu'il y a 3 axes "intéressants" retenus.
Bref,
acp1$quali.sup renvoie 5 tableaux:
1. Celui des coordonnées des "noms" que peuvent prendre la variable qualitative (donc "otarie, baleine, phoque, etc...)  selon les 3 axes. (noms des genres en lignes, n° des axes en colonnes)
2. Même chose mais pour les cos^2
3. Même chose mais pour les v.test
4. Une liste appelée "dist" avec une valeur numérique pour chaque genre
5. Une liste eta2 avec une valeur numérique pour chaque axe
Est-ce normal ? ou il y a t il déjà un problème à ce niveau ?

En tous cas, merci d'avance pour la réponse :)

**Comment by juba** [comment]
Bon, ben tout semble normal.

Et dans explor, si tu vas dans l'onglet "individus - graphique", dans la barre latérale tu n'as pas de liste déroulante "Couleur" ? Normalement c'est là que tu peux choisir de colorier les points selon les modalités d'une variable quali supplémentaire.

À noter qu'explor marche aussi avec les résultats générés par les fonctions d'ade4 normalement.

**Comment by CroixJeremy2** [comment]
okok
Non, dans cette fenêtre, à gauche, je ne peux choisir "que":
_le choix des axes X et Y
_la taille des points
_l'opacité des points
_afficher ou non les étiquettes
_la taille des étiquettes
_garder ou non les animations
_sélection lasso
_obtenir le code R
_exporter en SVG

Peut être que le problème vient du faite que je n'ai qu'une seule colonne variable qualitative ? je vais tester avec une deuxième "inventée" pour voir si les couleurs sont disponibles. Et donc savoir si le problème est en amont de explor ou non.
EDIT: l'ajout d'une seconde variable qualitative, ne fait pas apparaître les couleurs... :(
 
Ahhhhhh, j'ai oublié de dire que dans le graphique appelé "variable-graphique", j'ai les couleurs et je peux choisir de mettre ou non les variables qualitatives via une case. Mais je ne comprend pas pourquoi quand je coche, il m'affiche sur CE graphique, les points (via une moyenne je suppose) des genres. Du coup, ça m'affiche sur le même graphique (le "variable-graphique"), le cercle des corrélations (ça c'est normal) mais AUSSI des points,qui normalement, appartiennent à un graphique des individus... (ça c'est étrange, et ça le fait aussi avec une seconde variable qualitative)

**Comment by juba** [comment]
Pour le fait que les variables quali supplémentaires apparaissent sur le graphique des variables, ça n'est pas un bug, car c'est tout à fait possible de représenter sur le même graphe.

Par contre ça devrait aussi apparaître sur le graphique des individus. Est-ce que vous auriez la possibilité de me transmettre vos données `M`, que je puisse tester directement, si ça ne pose pas de problème de confidentialité ou autre ?

**Comment by CroixJeremy2** [comment]
Aucun problème !

- Données de bases:
[especes.txt](https://github.com/juba/explor/files/915973/especes.txt)

- Mon code:

#Importation des données dans la matrice D
D=read.table(file="C:/Users/Jérémy/Desktop/especes.txt",header=T)
attach(D)

#Création d'une matrice M, mieux réarrangée que la matrice originelle D
M=D
rownames(M)=D[,1]
colnames(M)=c(colnames(D)[2:ncol(D)],"Gr.phyllo")
M[,1:8]=D[2:9]
M[,9]=c("Phocinae","Phocinae","Phocinae","Otariidae","Phocinae","Phocinae","Mirounga","Mirounga","Otariidae","Otariidae","Otariidae","Balaenopteridae","Canidae","Primate")
M=as.data.frame(M)

#Réalisation de l'ACP sur la matrice M
library(FactoMineR)
#data("M")
acp1=PCA(M, quali.sup=9, scale.unit=T, ncp=3 ,graph=F)
#scale.unit=T pour centrer ET REDUIRE les résultats
#ncp=3 car 3 axes expliquent la majorité (~91-92%) des résultats
#graph=F pour ne pas générer de graphique dans R Studio puisqu'on génére un graph avec explor
#quali.sup= 9 car la 9eme colonne de M est une variable qualitative

#Visualisation des résultats de l'ACP
library(shiny)
library(explor)
explor(acp1)

**Comment by juba** [comment]
Et bien effectivement, il y avait un joli petit bug pour les ACP. Il devrait être désormais résolu dans la version de développement d'explor, que vous pouvez installer avec :

```r
install.packages("devtools")
devtools::install_github("juba/explor")
```

Merci d'avoir pris le temps de rapporter le bug et de me transmettre vos données ! Et n'hésitez pas à me signaler si ça ne fonctionne toujours pas.

Ah, et sinon, en passant : ne *jamais* utiliser `attach()` dans un script R :)

**Comment by CroixJeremy2** [comment]
C'est noté pour attach() ;)

Hmm, pour ce qui concerne les 2 lignes de codes pour installer "la version de développement", et bien:

- la première ligne de code a l'air de fonctionner (^.^) puisque R Studio renvoie en dernière ligne:
package ‘devtools’ successfully unpacked and MD5 sums checked

- la seconde ligne de code par contre... renvoie:

 installing *source* package 'explor' ...
Warning in file(file, if (append) "a" else "w") :
  impossible d'ouvrir le fichier 'C:/Users/Jirimy/Documents/R/win-library/3.3/explor/DESCRIPTION' : No such file or directory
Error in file(file, if (append) "a" else "w") : 
  impossible d'ouvrir la connexion
ERROR: installing package DESCRIPTION failed for package 'explor'
 removing 'C:/Users/Jérémy/Documents/R/win-library/3.3/explor'
 restoring previous 'C:/Users/Jérémy/Documents/R/win-library/3.3/explor'
Error: Command failed (1)

- J'ai remarqué que dans la ligne:
  impossible d'ouvrir le fichier 'C:/Users/Jirimy/Documents/R/win-library/3.3/explor/DESCRIPTION' : No such file or directory
il y a écrit Jirimy au lieu de Jérémy, ce qui doit probablement poser problèmes, non? Comme je débute avec R Studio, est ce que l'erreur provient de moi ?

**Comment by juba** [comment]
Ah, c'est bizarre, mais j'ai déjà eu de nombreux problèmes avec les accents dans les noms d'utilisateur sous Windows. Sinon, vous pouvez essayer de télécharger le zip de la derinère version de dev via ce lien : 

https://github.com/juba/explor/archive/master.zip

Et dans RStudio, aller dans "Packages", "Install", dans "Install from" choisir "Package archive file" puis choisir le fichier master.zip précédemment télécharger et voir si ça marche... (c'est pas sûr).

**Comment by CroixJeremy2** [comment]
Ahhh, je me doutais bien que ça provenait de moi et mes accents :D 

Téléchargement ok
Packages, Install, Package archive file (.zip ; tar.gz), Browse du fichier explor-master.zip ok
Mais R Studio renvoie:
Installing package into ‘C:/Users/Jérémy/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

Et c'est tout :/

**Comment by juba** [comment]
Ah... Et du coup il ne finit pas l'installation ? Et explor ne marche toujours pas ?
Autre solution qui marche des fois : lancer l'interface de R par défaut sous Windows (pas RStudio), exécuter les deux lignes dans la console : 

```r
install.packages("devtools")
devtools::install_github("juba/explor")
```

**Comment by CroixJeremy2** [comment]
Nope... Ça ne reste même pas bloqué dans un hypothétique "chargement ou installation" car l'icone stop ne s'allume pas comme dans un "chargement ou installation" d'un package. De plus, ça me "rend la main" sur R Studio, c'est à dire que > réapparaît et je peux à nouveau utiliser R Studio. Je ne sais pas si je suis assez clair :S 

Nope, explor ne m'affiche toujours pas les couleurs dans le graphique des individus...

NB: quand je fais la petite manipulation pour demander l'installation via le fichier.zip, R Studio fait la commande:
install.packages("C:/Users/Jérémy/Downloads/explor-master.zip", repos = NULL, type = "win.binary")

Ah oui pas bête de faire ça avec R directement ! Mais ça me renvoie les mêmes lignes avec l'erreur Jirimy...

**Comment by juba** [comment]
Décidément...

Et en essayant d'installer directement le fichier suivant : 
[explor_0.3.2.tar.gz](https://github.com/juba/explor/files/916766/explor_0.3.2.tar.gz)

Est-ce que ça fonctionne ?

**Comment by CroixJeremy2** [comment]
Il se passe plus de chose, mais toujours le même problème avec le Jirimy. R Studio renvoie:

Installing package into ‘C:/Users/Jérémy/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
 installing *source* package 'explor' ...
Warning in file(file, if (append) "a" else "w") :
  impossible d'ouvrir le fichier 'C:/Users/Jirimy/Documents/R/win-library/3.3/explor/DESCRIPTION' : No such file or directory
Error in file(file, if (append) "a" else "w") : 
  impossible d'ouvrir la connexion
ERROR: installing package DESCRIPTION failed for package 'explor'
 removing 'C:/Users/Jérémy/Documents/R/win-library/3.3/explor'
 restoring previous 'C:/Users/Jérémy/Documents/R/win-library/3.3/explor'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Jérémy\Documents\R\win-library\3.3" "C:/Users/Jérémy/Downloads/explor_0.3.2.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/Jérémy/Downloads/explor_0.3.2.tar.gz’ had non-zero exit status

**Comment by CroixJeremy2** [comment]
Peut être qu'en incorporant la correction du bug directement dans le package explor, et non dans "la version de développement" pourrait fonctionner ? Car quand je réinstalle explor via install.package("explor"), R Studio renvoie la même première ligne de code, à savoir : 
Installing package into ‘C:/Users/Jérémy/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Mais là l'installation se termine correctement :) puisque R Studio affiche ensuite:
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/explor_0.3.1.zip'
Content type 'application/zip' length 106184 bytes (103 KB)
downloaded 103 KB

package ‘explor’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Jérémy\AppData\Local\Temp\RtmpGIzWXX\downloaded_packages

**Comment by juba** [comment]
Certes, mais je ne peux pas publier une nouvelle version sur le CRAN à chaque modification, d'abord car c'est un processus qui prend un peu de temps, et ensuite car les mainteneurs du CRAN demandent de laisser un délai entre les mises à jour pour ne pas trop les surcharger... Mais c'est sûr que la prochaine publication devrait résoudre votre problème.

Une autre piste potentielle, mais pas sûr non plus que ça fonctionne :

https://support.rstudio.com/hc/en-us/community/posts/218632788/comments/224385767

**Comment by CroixJeremy2** [comment]
Je m'en doutais un petit peu et je comprends très bien, j'aurais au moins essayé ;)

Bref, j'ai regardé le lien, et cherché autre part pour voir si ce problème avait été réglé auparavant. Malheureusement, je n'ai pas trouvé, et ai déjà perdu bcp trop de temps. Du coup, j'ai créé une autre session sur mon PC, avec un nom d'utilisateur SANS accents, afin de faire tourner le programme .R sur cette session. Et effectivement, dans cette session, l'installation d'explor en "version de développement" s'est bien passée, et ALELOUYA les couleurs et ellipses sont là !!! (oui je suis heureux). Donc, le 2ème problème provient bien des accents...

Bref, **_both problems are solved_**, tout fonctionne. Je tiens à te remercier juba, pour l'aide que tu m'as apporté, et de la rapidité à laquelle tu répondais (^.^)
Mes profs ne semblent pas être au courant qu'un tel outil, explor, existe à l'heure actuelle pour visualiser, de façon interactive, les ACP par exemple. Je compte donc faire connaître ton excellent travail à plusieurs personnes car tu le mérites ! Encore merci juba, je te souhaite une très bonne continuation (^.^)/
