### ISSUE TITLE
Trouble with ACM (ade4)

### ISSUE THREAD

**Issue by Aurorim** [juba/explor#16]
Bonjour,

Le package a l'air super chouette, faut-il une version très récente de R pour l'utiliser? Je l'ai téléchargé avec ma version 3.2.5 (donc pas de package FactoMineR), et lorsque j'essaie de lancer explor() sur une ACM lancée par ade4, le message ci-dessus apparait:

Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "c('matrix', 'double', 'numeric')"

Du coup dans la foulée j'ai testé sur les données iris du package ade4 (toujours lui) en voulant voir si c'était identique pour l'ACP. La réponse est oui, même erreur.

Me disant que c'était un souci d'explor, j'ai fait comme indiqué sur un autre fil, et suis passée par:

devtools::install_github("juba/explor")

à quoi a répondu le dialogue suivant

* installing *source* package 'explor' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'scales' 0.4.0 is being loaded, but >= 0.4.1 is required
ERROR: lazy loading failed for package 'explor'

Je crois que mon ordinateur très encrassé n'aide pas non plus...

**Comment by juba** [comment]
Bonjour,

Est-ce que vous utilisez la dernière version d'ade4 ?

**Comment by Aurorim** [comment]
La 1.7-6, oui.

Bon en revanche après avoir essayé de télécharger explor depuis GitHub, lorsque j'essaie de charger explor, ça me renvoie:

> library(explor)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  l'espace de noms ‘scales’ 0.4.0 est en train de charger, mais >= 0.4.1 est requis
In addition: Warning message:
le package ‘explor’ a été compilé avec la version R 3.2.5 
Error: le chargement du package ou de l'espace de noms a échoué pour ‘explor’

**Comment by juba** [comment]
Et en faisant juste : 

```r
install.packages("scales")
```

Qu'est-ce que ça donne ?

**Comment by juba** [comment]
Et juste pour être sûr, c'est bien explor 0.3.1 que vous utilisez ?

**Comment by Aurorim** [comment]
Ca fonctionne pour scales, et oui pour la version.

**Comment by juba** [comment]
Et maintenant que scales a été mis à jour, vous arrivez à charger explor ?

**Comment by Aurorim** [comment]
Oui, parfait, merci beaucoup! Bon, en fait je suis passée par une étape de suppression de tous les packages suivis de leur téléchargement - et ensuite ça a fonctionné.

Du coup l'interface s'est ouverte sur internet explorer, elle fonctionne sur tous les navigateurs?

**Comment by juba** [comment]
Je n'ai pas testé sur Internet Explorer. J'aurais tendance à plutôt recommander une version récente de Chrome ou Firefox (ou équivalents), mais si ça fonctionne sous IE, ma foi...

Content que vous ayez pu résoudre le problème en tous cas !

**Comment by Aurorim** [comment]
A la seconde tentative (pour voir si ce n'était pas juste un coup de chance), c'est bien l'interface Shiny qui est apparue sur R Studio.

Je pense que ma version ade4 n'était pas à jour au départ, d'où un processus un peu poussif.

Merci encore pour la réactivité, et pour le package bien pratique!

**Comment by juba** [comment]
Je vous en prie. Bon week-end !
