### ISSUE TITLE
Color of individual depending on supplementary variables

### ISSUE THREAD

**Issue by ClaireLsce** [juba/explor#18]
I did a PCA with FactormineR and I have in my dataset two supplementary variables (qualitatives). I tried explor and it's a very nice package. Is it possible to modif the color of indiviuals depending on one af these two variables? In my case I did not have the choice of the color.
Thank you in advance, 

Claire

**Comment by juba** [comment]
Yes, this is a known bug in the current CRAN version. It should be fixed in the development version, which you can install with :

```
install.packages("devtools")  # If necessary
devtools::install_github("juba/explor")
```

**Comment by ClaireLsce** [comment]
This is perfect, thanks a lot! 


De: "Julien Barnier" <notifications@github.com> 
À: "juba/explor" <explor@noreply.github.com> 
Cc: "ClaireLsce" <claire.froger@lsce.ipsl.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 30 Mai 2017 15:30:58 
Objet: Re: [juba/explor] Color of individual depending on supplementary variables (#18) 



Yes, this is a known bug in the current CRAN version. It should be fixed in the development version, which you can install with : 
install.packages("devtools")  # If necessary
devtools::install_github("juba/explor")
