### ISSUE TITLE
Choice of color

### ISSUE THREAD

**Issue by novitch** [juba/explor#19]
Hello Julien,
It is more a request than an issue. I am pretty sure that your tool will be use by any R users in my lab if we can choose the color of our group. Esthetics is one of the most important criteria for them i'm sure.

If it will be possible one day,

Thanks for your tool again,

**Comment by juba** [comment]
Hi,

I don't think I will implement it in `explor`. But if you export a graph as R code, you'll see that it uses the `scatterD3` function. You can then add arguments to this function to set the colors as you like. See : 

https://rawgit.com/juba/scatterD3/master/vignettes/introduction.html#mapping-colors-symbols-size-and-opacity-to-variables

Would this suit your needs ?

**Comment by novitch** [comment]
Yes i was looking for this solution actually. 

Thanks
