### ISSUE TITLE
Variable labels

### ISSUE THREAD

**Issue by larmarange** [juba/explor#23]
Hi,

regarding labels of points on the variable graph, it currently displays the modalities. The get the variable, you need to look at point colors. 

Sometimes, it would be easier to display as label "Name - Modality". Would you consider adding such option?

Best regards

**Comment by juba** [comment]
Yes, good idea, I just added a "prepend variable name to labels" option to the MCA variable plot. Thanks for the suggestion !

**Comment by larmarange** [comment]
Thanks to you

Joseph Larmarange

Le jeu. 23 mai 2019 à 10:40, Julien Barnier <notifications@github.com> a
écrit :
