### ISSUE TITLE
Not possible to zoom in the pca plot

### ISSUE THREAD

**Issue by eloichazelas** [juba/explor#24]
Hi, just a small issue, as mentionned in the title, I use the explor package to export a PCA plot but I can't zoom in on the plot, although I remember it was possible before. I need to do it because I have a wealth of labels that overlap if I don't zoom in.

Also in the R window the labels no longer appear when they used to (and they still appear on the browser window, even if I didn't modified the minimal contribution item). 

Plot without label : 
![image](https://user-images.githubusercontent.com/54318734/64534706-35640780-d316-11e9-90bc-e3f20903eeab.png)

Thanks,

**Comment by juba** [comment]
Hi, could you tell me what version of RStudio you are using ?

**Comment by eloichazelas** [comment]
3.5.2

**Comment by juba** [comment]
That's your version of R, but what is the version of RStudio (if that's what you're using) ?

**Comment by eloichazelas** [comment]
sorry 1.1.447

**Comment by juba** [comment]
Are you able to upgrade your RStudio to the latest 1.2 version ? It's quite possible the bug is coming from here, as the web rendering engine of 1.1 is quite old and has been replaced in 1.2.

**Comment by eloichazelas** [comment]
Ok I will try and let you know. Thanks!

**Comment by eloichazelas** [comment]
Thanks it worked perfectly! Cheers
