### ISSUE TITLE
Export biplot (ACM)

### ISSUE THREAD

**Issue by ghost** [juba/explor#26]
Hello, 

Your package is very usefull, thanks a lots for the developpment. 

I have just a little issue about exporting the Biplot into a SVG file. I'm exploring an ACM, export works for individual and variable plot but not for biplot. I tested on MAC OS X and Windows computer. If you need some session informations you can ask me but i think it's a little bug on the code.

**Comment by juba** [comment]
I just tried with an example ACM and it worked. Could you give more informations about the way it is not working ?
