### ISSUE TITLE
Any way to insert `explor::explor()` into a larger shiny app? Or at least a way to add custom CSS to it?

### ISSUE THREAD

**Issue by daattali** [juba/explor#27]
If we have a shiny app that lets a user create an analysis object, it would be nice to be able to integrate the explor app into it.

If this is not easily supported, it would still be useful to at least be able to pass in custom UI and server code to execute, or something even more basic would be to allow passing in CSS files.

**Comment by juba** [comment]
Well, explor is a tool to be used inside your workflow to ease the exploration of results. As a shiny app it can be put online as is, but it is not intended to be integrated inside another app.

Explor per se is just a link between the underlying statistical packages, and `DT` and `scatterD3` for visualizations, it does nothing really that complicated. So I think maybe you would be better just integrating those tools in your own app.

**Comment by daattali** [comment]
Fair!
