### ISSUE TITLE
exporting results for PCA

### ISSUE THREAD

**Issue by chisin** [juba/explor#28]
Hello, I have been using explor() for visualizing the results of dudi.PCA. I would like to export the info of the variables contributing to the different axes (in particular of the ones contributing most, which I suppose should be the ones with the highest "contrib" values). I tried running the "non-shiny" commands (e.g.
res.var <- get_pca_var(res.pca)
res.var$coord          # Coordinates
res.var$contrib        # Contributions to the PCs
res.var$cos2           # Quality of representation 
), however the numbers do not correspond (e.g. the res.var$contrib command gives "0.00762", while explor shows "0.01". Is it because explor is rounding values? Thank you, C.

**Comment by juba** [comment]
You use the `dudi.pca` function from the `ade4` package ?
Where does the `get_pca_var` function comes from ?

**Comment by juba** [comment]
If I'm not mistaken, and if you're using `dudi.pca`, contributions values should be computed with :

 ```r
inertia.dudi(res.pca, col.inertia = TRUE)$col.abs
```

And yes, values are rounded to two decimals in `explor` tables, that should explain the differences...

**Comment by chisin** [comment]
Yes, I use the dudi.pca function from ade4, combined with factoextra package (following instructions found here: http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/119-pca-in-r-using-ade4-quick-scripts/ ). Thank you for the prompt answer!
