### ISSUE TITLE
Wrong eigenvalues histogram (explained variance)

### ISSUE THREAD

**Issue by zenn1989** [juba/explor#31]
Eigenvalue histogram on first tab in shiny output gave eigenvalues histogram / table only for PC1 dimension. It seems not to be useful to overview PCA results "explained variance" from this plot, because only first dimension (PC1) are shown. 
You can easy repeat this by:
```
fit <- prcomp(data)
summary(fit)
```
and in `summary` output you will see the row `Proportion of variance`. In other way you can find clear eigenvalues from sdev:
```
fit$sdev ^ 2
```
There is some attachment to make it clear. 
![Screenshot_54](https://user-images.githubusercontent.com/3446897/81502909-8be07600-92e9-11ea-88f7-f612c94e4ced.png)

**Comment by juba** [comment]
You're right ! I was computing the percentage of variance on standard deviation instead of eigenvalues. Thanks for letting me know, it should be fixed now !
