### ISSUE TITLE
The font of the labels is white

### ISSUE THREAD

**Issue by Laur-e** [juba/explor#33]
Bonjour,
Je ne sais pas si ce problème a été traité ailleurs mais je viens de mettre à jour R et tous mes packages (j'ai fait une erreur et je n'ai pas pu les importer de la version précédente de R) et maintenant quand j'utilise explor, toutes les étiquettes des variables sont blanches et je ne peux pas les voir... Les points par contre apparaissent bien en couleurs. Avez-vous une idée d'où peut venir le problème ? 
Merci d'avance !

**Comment by juba** [comment]
Bonjour,

Vous avez essayé avec la version de développement ? Et est-ce que vous pourriez enregistrer le graphique qui s'affiche mal en SVG et m'envoyer le fichier ?

**Comment by Laur-e** [comment]
Merci pour votre réponse !
C'est-à-dire la version de développement ? J'utilise RStudio et j'ai installé le package explor depuis le CRAN.
Voici le fichier SVG de mon ACM.

[SVG.txt](https://github.com/juba/explor/files/5420703/SVG.txt)

**Comment by juba** [comment]
Quand je parlais de la version de développement je voulais dire celle qui est actuellement sur Github mais pas encore sur le CRAN. Il y a peu de chances que ça résolve le problème, mais sait-on jamais... 

Pour l'installer il faut que vous installez le package "remotes" et ensuite que vous lanciez la commande suivante dans la console : 

```r
remotes::install_github("juba/scatterD3")
remotes::install_github("juba/explor")
```

J'arrive à ouvrir le fichier SVG généré et je vois bien les labels, par contre il y a des soucis d'encodage de caractères (mais je ne suis pas certain que ce soit la source du problème). Si la version de développement ne résout pas le problème, est-ce que vous pouvez essayer de voir si le code suivant génère le même problème ?

```r
library(FactoMineR)
library(explor)

data(hobbies)
mca <- MCA(hobbies[1:1000,c(1:8,21:23)],quali.sup = 9:10, quanti.sup = 11, ind.sup = 1:100)
explor(mca)
```

**Comment by Laur-e** [comment]
Non ça n'a pas marché... Et oui c'est la même chose avec l'autre ACM...
Je vous envoie le fichier SVG de l'ACM avec les datas "hobbies" (en fichier compressé car le format du fichier SVG n'est pas supporté sinon). 

[SVG2.zip](https://github.com/juba/explor/files/5421332/SVG2.zip)

**Comment by juba** [comment]
Hmm c'est assez étrange, je n'arrive pas à reproduire le problème. Est-ce que vous pourriez m'envoyer une copie d'écran du graphique avec les labels en blanc ? 

Et si vous ouvrez un des deux fichiers SVG que vous m'avez envoyé directement dans votre navigateur, est-ce que vous avez également le problème ?

**Comment by Laur-e** [comment]
Effectivement si j'ouvre l'ACM avec mon navigateur (en cliquant sur "Open in Browser") je vois bien les couleurs ! Ça ne règle pas le problème mais c'est déjà ça.

![Sans titre 1](https://user-images.githubusercontent.com/73238156/96853788-10b7ea00-145b-11eb-8d55-3f9c7bd0f48e.jpg)

**Comment by juba** [comment]
Dernière question (enfin pour l'instant) : est-ce que vous pouvez m'indiquer quelle version de RStudio vous utilisez ? Et est-ce que vous avez encore le problème du coup si dans RStudio vous cliquez sur "Open in browser" pour visualiser le graphique dans votre navigateur ?

**Comment by Laur-e** [comment]
Olala j'ai honte, c'était juste ça, j'ai mis à jour RStudio et ça marche (j'utilisais la version 1.1) ! 
Je pensais que la mise à jour de R avait mis à jour RStudio mais ce n'était pas le cas...
Merci et désolée pour la perte de temps !

**Comment by juba** [comment]
Ah, voilà ! Effectivement la version 1.1 est ancienne, et les versions plus récentes ont changé le moteur de rendu HTML.

Pas de souci, et content que le problème soit réglé !

**Comment by Laur-e** [comment]
Merci pour tout ce que vous faites !
