### ISSUE TITLE
Probleme des couleurs

### ISSUE THREAD

**Issue by melissa74** [juba/explor#35]
Bonjour !
Tout d'abord merci pour cette interface, c'est un vrai bonheur à manipuler !
J'ai remarqué qu'une personne (ramahandrison) avait déjà posé la question mais je n'ai pas pu avoir la réponse.

Le reste fonctionne très bien mais je ne peut pas modifier les couleurs. Pourriez-vous m'aider ?

Merci encore infiniment, c'est un vrai bonheur à utiliser !
Excellente journée à vous

**Comment by juba** [comment]
Bonjour,

Vous voulez parler de modifier la palette utilisée pour colorer les points selon leur modalité ? Ce n'est pas possible directement dans explor, et je ne pense pas que j'ajouterai cette possibilité car l'interface est déjà bien chargée.

Une possibilité par contre est d'utiliser la fonction "récupérer le code R" qui permet d'obtenir le code qui produit le graphique, et d'ensuite ajouter un argument `colors` à la fonction qui génère le graphe (la fonction est différente selon le type d'analyse, par exemple pour une ACM il s'agira de `MCA_ind_plot`, etc.).

Pour savoir comment utiliser `colors` vous pouvez regarder l'aide de la fonction `scatterD3` ici : 

https://juba.github.io/scatterD3/articles/introduction.html#color-1

Désolé tout cela est un peu compliqué, mais en théorie ça devrait marcher. N'hésitez pas à me signaler si ça n'est pas le cas.
