### ISSUE TITLE
Is there an independent Shiny available?

### ISSUE THREAD

**Issue by ShixiangWang** [juba/explor#36]
I mean, is it possible to call `explor::explor()` without arguments and start the explor Shiny which providing input the data?

Best,

Shixiang

**Comment by juba** [comment]
I'm not sure to understand what you want to do. `explor` can only be started from an R session by passing it the object to apply it to. It is not intended to be integrated into another shiny app...

**Comment by ShixiangWang** [comment]
Okay, thanks.
