### ISSUE TITLE
Graphs are not displayed 

### ISSUE THREAD

**Issue by V-LF** [juba/explor#38]
Bonjour, 

J'ai déposé un message sur votre page de presentation de explor mais je crois que ce n'est pas le lieu consacré (je débute en code et ne connaissait pas github...). 
J'aimerais utiliser explor pour travailler la visualisation d'une ACM. J'utilise FactoMineR (la fonction MCA). Lorsque l'interface Shiny s'ouvre, les graphiques des variables et des individus ne s'affichent pas. 
Je me demande si c'est une question de version de R (je travail sur la version 3.6.3) ou de explor (0.3.6) ou encore une question de navigateur (automatiquement, R ouvre Shiny sur safari). 
J'ai essayé sur deux bases de données différentes : l'une pour une ACM et une autre pour une ACP. J'ai l'impression que le problème ne viens pas des données. Néanmoins, je précise qu'avec l'ACM, je reçois un message d'erreur : des entrées de longueur nulle ne peuvent être mélangés avec celles de longueur non nulle.
Cordialement, 
Victor

**Comment by juba** [comment]
Bonjour,

Ah, je viens de répondre sur Quanti mais je vais aussi répondre ici, ce sera plus propice à une éventuelle discussion.

La première chose que vous devriez faire serait de mettre à jour explor (disponible en version 0.3.9) et si possible R. Je pense que ça devrait résoudre le problème. Si ça n'est pas le cas n'hésitez pas à me le signaler.

**Comment by V-LF** [comment]
Bonjour, 
Alors j'ai mis à jour explor et shiny par la même occasion!  
Mais le problème était ailleurs et j'ai finalement trouvé : il faut éviter safari pour l'ouverture. En ouvrant l'onglet dans le navigateur et en copiant/collant l'adresse dans mozilla, le graphique s'ouvre correctement.  
Bonne journée et merci pour votre réponse, 
Victor

**Comment by juba** [comment]
Ah effectivement c'est possible que certains navigateurs un peu anciens puissent poser problème. Vous n'utilisez pas RStudio ?

En tous cas tant mieux si le problème est résolu !

**Comment by V-LF** [comment]
Oui j'utilise Rstudio mais la fenêtre Rstudio n'affichait pas le graphique non plus. Il n'y que des problèmes avec safari et malheureusement on ne peut pas le supprimer!

**Comment by juba** [comment]
Je ne sais pas quelle est votre version de RStudio mais normalement une version récente devrait pouvoir afficher les sorties d'explor. En tous cas ça peut valoir le coup d'essayer pour éviter les manipulations d'ouverture dans un autre navigateur que celui par défaut.

**Comment by V-LF** [comment]
Merci pour ces conseils. J'utilise la version 3.6.3. Je n'ai pas eu ce problème lorsque j'utilise MCAshiny (qui soit disant passant est moins sympathique que explor!) dans safari ce qui explique que je ne me soit pas douté que le navigateur soit à l'origine du problème

**Comment by juba** [comment]
Oui, pardon, je parlais de la version de RStudio, pas de celle de R. `explor` utilise du JavaScript pour les graphiques, du coup il peut effectivement y avoir des soucis de compatibilité avec des versions de navigateur ou de RStudio un peu anciennes.

**Comment by V-LF** [comment]
Ah je comprends... C'est en effet une version qui date de 2017 (Rstudio 1.1.383)

**Comment by juba** [comment]
Houla effectivement 😅

Du coup je vous conseille de mettre à jour à la dernière version. Vous aurez des fonctionnalités supplémentaires, et explor devrait fonctionner directement dans RStudio.

**Comment by V-LF** [comment]
Ah! Je l'avais installé pour un cours et puis laissé végéter sur mon bureau! Je vais suivre votre conseil
