### ISSUE TITLE
Font Awesome warning

### ISSUE THREAD

**Issue by jl5000** [juba/explor#39]
When running explor, I get the following warning:

> This Font Awesome icon ('file-image-o') does not exist:
> * if providing a custom `html_dependency` these `name` checks can 
>  be deactivated with `verify_fa = FALSE`

This is the code I run to produce it:

`explor::explor(prcomp(iris[,1:4]))`

**Comment by juba** [comment]
Indeed, this should now be fixed in the development version.

Thanks for taking the time to report the issue !
