### ISSUE TITLE
Limit the plot to most contributive or highest cos2

### ISSUE THREAD

**Issue by gabrielparriaux** [juba/explor#41]
Hello,

In a simple categorical analysis, I try to use the field "Contribution min pour afficher l'étiquette" to limit the number of individuals displayed on the plot, but it doesn’t seem to have any effect… no change on the plot when I enter any value.

It would be great to have a way to limit the number of individuals (or variables) to display according to contrib or to cos2 (a slider or a field value that we could enter — something that would work live would be even greater). 

Does it exist and I didn’t see it?

Thanks a lot, it’s a great tool!

Gabriel

**Comment by juba** [comment]
Indeed, the feature is broken, thanks for reporting it.

You can make it work by disabling animations (you can uncheck the checkbox at the bottom of the sidebar), but I'll take a look into the issue.

**Comment by gabrielparriaux** [comment]
Ah ok! Yes, if I disable animations, it work. 

It would be great to be able to manage this feature separately for rows and columns, and also to choose between contribution or cos2 as a factor. 

A little bit like what we can do with this kind of function:
```r
fviz_ca_biplot(res.ca, repel = TRUE, axes = 1:2 , select.row = list(cos2 = 20), select.col = list(cos2 = 5))
```

Maybe some addition in the future?

Thank your for help,
Gabriel

**Comment by juba** [comment]
Ok, so the issue should be fixed now in the development version, _ie_ the field "Contribution min pour afficher l'étiquette" should work again even with animations enabled.

Your request to allow to filter either row or column labels in CA, or to be able to filter on cos2, is perfectly relevant. Unfortunately I tend to limit the addition of new controls to the interface which is already quite crowded. So I think that for the moment I will leave it as it is, and you can, as in your example, use other packages such as Factoextra if you want to generate more "precise" plots.

**Comment by juba** [comment]
Ah, one thing I forgot : for the fix to be available you have to install the development versions of both `explor` and `scatterD3`, as explained in the `README` file.

**Comment by gabrielparriaux** [comment]
> Ok, so the issue should be fixed now in the development version, _ie_ the field "Contribution min pour afficher l'étiquette" should work again even with animations enabled.
> 
> Your request to allow to filter either row or column labels in CA, or to be able to filter on cos2, is perfectly relevant. Unfortunately I tend to limit the addition of new controls to the interface which is already quite crowded. So I think that for the moment I will leave it as it is, and you can, as in your example, use other packages such as Factoextra if you want to generate more "precise" plots.

Thanks a lot! No problem for the complementary filters proposition, I completely understand that you want to keep the interface simple.
