### ISSUE TITLE
speMCA_varsup not working + proposal to fix it

### ISSUE THREAD

**Issue by label42** [juba/explor#43]
Hello,

It seems that the `speMCA_varsup` fonction isn't working. When I use it, I get this error : 

```
> speMCA_varsup(speMCA_prat, d_sup_csACM)
Error in if (xi > xj) 1L else -1L : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In xtfrm.data.frame(x) :
  impossible d’utiliser xtfrm sur un tableau de données (data frame)
2: In Ops.factor(xi, xj) :
  ‘>’ n'est pas pertinent pour des variables facteurs
```
The dataframe of sup variables I'm using has the same number of row then the one used to compute de speMCA, and contain no NA value.

I think I have identified the issue and found a solution to the problem.

In the file `utils.R`, line 18 : 

\- `l <- GDAtools::varsup(mca, df[, name])`
\+ `l <- GDAtools::varsup(mca, df[[name]])`

I didn't used the pull request section of the github repo as I am not really familiar with the tool and wasn't 100 % sure of my proposal. Anyway, the modification solved the issue for me.

Abel

**Comment by juba** [comment]
Hi,

I can't reproduce the issue with a sample dataset. Did you try with the development version of explor ? If this is the case, would you have a reproducible example you could share ?

Anyway, thanks for taking the time to report the issue !

**Comment by label42** [comment]
I'm using explor_0.3.9 AND GDAtools_1.8 

I did not try with the development version of explor.

**Comment by juba** [comment]
Could you try with the development version ? There are two fixes regarding supplementary variables in `speMCA` since explor 0.3.9, so maybe your issue is already fixed too.

You can install the development version with : 

```r
install.packages("remotes")  # If necessary
remotes::install_github("juba/scatterD3")
remotes::install_github("juba/explor")
```
