### ISSUE TITLE
masquer des modalités sur le graph des variables

### ISSUE THREAD

**Issue by Victoria-Brun** [juba/explor#46]
Bonjour,
J'aurais aimé savoir s'il était possible, dans l'interface explor, de masquer certaines modalités (et pas des variables entières) ?
Je sais le faire avec le fonction plot de FactoMineR, mais l'argument ne semble pas convenir au code extrait de explor (ci-dessous).

Merci par avance,
Victoria Brun

J'avais essayé d'exécuter ça, sans succès :
res <- explor::prepare_results(res.acmcollab2)
explor::MCA_var_plot(res, xax = 1, yax = 3, var_sup = TRUE, var_sup_choice = "plateforme_outilcollab",
                     var_lab_min_contrib = 0,
                     col_var = "Variable", symbol_var = "Type", size_var = NULL,
                     size_range = c(10, 300), labels_size = 10, point_size = 56, transitions = TRUE,
                     labels_positions = "auto", labels_prepend_var = FALSE, xlim = c(-2, 1, 75),
                     ylim = c(-1, 89, 1, 86),
                     selectMod=which(!((1:nrow(res.acmcollab2$var$coord))%in%grep("non",rownames(res.acmcollab2$var$coord))))
                     )

**Comment by juba** [comment]
Malheureusement ça n'est a priori pas possible. `selectMod` est effectivement un argument des fonctions `plot` de FactoMineR, mais ce ne sont pas ces fonctions qui sont utilisées dans explor...

**Comment by Victoria-Brun** [comment]
Merci beaucoup pour votre réponse !
