### ISSUE TITLE
How can I share the explor output with my friends

### ISSUE THREAD

**Issue by 419kfj** [juba/explor#47]
I tried to export to RPub but shiny is not supported.

Are there any methods to share the out put of explor to my friends?

**Comment by juba** [comment]
If you get the R code of one of the dynamic charts in explor interface, you can use it to reproduce it as an HTML widget. If I'm not mistaken, these widgets can be embedded in RMarkdown or Quarto documents.

**Comment by 419kfj** [comment]
Thank you for your quick reply ;-).

I tried it. I understand I can share the result of the map. Is it impossible to share the left pain of explor (total UI of explor )?

**Comment by juba** [comment]
Unfortunately no, `explor` is in fact a shiny app, so to run it you would need a shiny server.
