### ISSUE TITLE
biplot (individuals and variables coordinates into a single graphic) 

### ISSUE THREAD

**Issue by lvaudor** [juba/explor#6]
Hello Julien,

This is not an issue but rather a request.

Being able to get the info about individuals and variables into a single plot (like what the "biplot" function in package stats or "scatter" in package ade4 does) would be great .

Anyway, this package is a great asset to produce beautiful PCA/CA/MCA results in a user-friendly way, and I'm going to show it to all people who come to me willing to carry out factorial analyses!...

**Comment by juba** [comment]
Hi Lise,

I tend to prefer having two separate plots for individuals and variables, but it really is a matter of taste (plus, you can't display both plots side by side in `explor` for the moment). A biplot-like view could be a nice enhancement. I'm currently working on some internal rewriting of both `scatterD3` and `explor`, but I'll try to take your suggestion into account.

And thanks for your feedback, I'm happy that `explor` can be useful !

**Comment by ginolhac** [comment]
Hello Julien,

I agree with Lise, a biplot option would be nice

**Comment by rdallet** [comment]
Hi Julien,

I would also be interested by a new tab displaying a biplot.

**Comment by juba** [comment]
Better late than never I guess, a biplot chart is now available in the development version, only for MCA results (but I'm not sure it really make sense for PCA anyway).

 I must tweak the form inputs a bit to make them more readable and usable but it should be functional.
